# Tasks to install latest neovim from appimage on GitHub
---

- name: "Ensure old neovim from repository is absent."
  ansible.builtin.apt: name=neovim state=absent

- name: "Landing place for nvim download exists."
  ansible.builtin.file:
    state: directory
    owner: root
    group: adm
    mode: '0750'
    path: "{{ nvim_dl_dir }}"

- name: "nvim v{{ neovim_version }} appimage downloaded."
  ansible.builtin.get_url:
    url: "{{ nvim_appimage_url }}"
    # checksum: "{{ nvim.checksum }}"
    dest: "{{nvim_dl_dir}}/nvim.appimage"
    mode: '0555'

- name: "Ensure 'nvim' v{{ neovim_version }} is installed."
  ansible.builtin.copy:
    src: "{{ nvim_dl_dir }}/nvim.appimage"
    dest: /usr/local/bin/nvim
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

...
# vim: foldlevel=2 : filetype=yaml.ansible :
