# tasks file for neovim
---

- name: Latest nvim and tree-sitter are installed.
  include_tasks: neovim_and_treesitter.yml
  when:
    - ansible_architecture == "x86_64"
    - neovim | bool == true

- name: "Neovim IDE-like configuration loaded."
  include_tasks: neovim_ide.yml
  when:
    - ansible_architecture == "x86_64"
    - neovim_ide | bool == true

- name: "Nightly neovim installed as 'nnvim'."
  become: true
  ansible.builtin.get_url:
    url: "{{ nightly_appimage_url }}"
    dest: /usr/local/bin/nnvim
    owner: root
    group: root
    mode: '0755'
  when:
    - ansible_architecture == "x86_64"
    - neovim_nightly | bool == true

...
# vim : filetype=yaml.ansible :
